// <auto-generated />
using System;
using CynapCRM.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419134723_ProductAPI")]
    partial class ProductAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Fichier", b =>
                {
                    b.Property<int>("Id_Fichier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Fichier"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Support")
                        .HasColumnType("int");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Taille")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Fichier");

                    b.HasIndex("Id_Support");

                    b.ToTable("Fichiers");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Lot", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Promo")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("Id_Produit");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Produit", b =>
                {
                    b.Property<int>("Id_Produit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produit"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prix_Creation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TVA")
                        .HasColumnType("int");

                    b.HasKey("Id_Produit");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Promotion", b =>
                {
                    b.Property<int>("Id_Promo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Promo"));

                    b.Property<string>("CodePromo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Pourcentage")
                        .HasColumnType("real");

                    b.HasKey("Id_Promo");

                    b.HasIndex("NumeroLot");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Support_Marketting", b =>
                {
                    b.Property<int>("Id_SupportMarketting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_SupportMarketting"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_SupportMarketting");

                    b.HasIndex("Id_Produit");

                    b.ToTable("Support_Markettings");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Fichier", b =>
                {
                    b.HasOne("CynapCRM.Services.ProductAPI.Models.Support_Marketting", "Support")
                        .WithMany("Fichiers")
                        .HasForeignKey("Id_Support")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Support");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Lot", b =>
                {
                    b.HasOne("CynapCRM.Services.ProductAPI.Models.Produit", "Produit")
                        .WithMany("Lots")
                        .HasForeignKey("Id_Produit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Promotion", b =>
                {
                    b.HasOne("CynapCRM.Services.ProductAPI.Models.Lot", "Lot")
                        .WithMany("Promotions")
                        .HasForeignKey("NumeroLot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Support_Marketting", b =>
                {
                    b.HasOne("CynapCRM.Services.ProductAPI.Models.Produit", "Produit")
                        .WithMany("Supports")
                        .HasForeignKey("Id_Produit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Lot", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Produit", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Supports");
                });

            modelBuilder.Entity("CynapCRM.Services.ProductAPI.Models.Support_Marketting", b =>
                {
                    b.Navigation("Fichiers");
                });
#pragma warning restore 612, 618
        }
    }
}
