// <auto-generated />
using System;
using CynapCRM.Services.FieldAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.FieldAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419134612_FieldAPI")]
    partial class FieldAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Objectif_Delegue", b =>
                {
                    b.Property<int>("Id_Objectif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Objectif"));

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValeurCible")
                        .HasColumnType("int");

                    b.HasKey("Id_Objectif");

                    b.HasIndex("Id_User_Delegue");

                    b.ToTable("Objectifs");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Planning_Visite", b =>
                {
                    b.Property<int>("Id_Planning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Planning"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.HasKey("Id_Planning");

                    b.HasIndex("Id_User_Delegue");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Rapport_Visite", b =>
                {
                    b.Property<int>("Id_Rapport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rapport"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRapport")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<int>("Id_Visite")
                        .HasColumnType("int");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Rapport");

                    b.HasIndex("Id_User_Delegue");

                    b.HasIndex("Id_Visite")
                        .IsUnique();

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Region", b =>
                {
                    b.Property<int>("Id_Region")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Region"));

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<string>("NomRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Region");

                    b.HasIndex("CodePostal");

                    b.HasIndex("Id_User_Delegue");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Visite", b =>
                {
                    b.Property<int>("Id_Visite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Visite"));

                    b.Property<DateTime>("DateVisite")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Medecin")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Pharmacien")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Planning")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Region")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id_Visite");

                    b.HasIndex("Id_Planning");

                    b.HasIndex("Id_User_Delegue");

                    b.ToTable("Visites");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Rapport_Visite", b =>
                {
                    b.HasOne("CynapCRM.Services.FieldAPI.Models.Visite", "Visite")
                        .WithOne("Rapport")
                        .HasForeignKey("CynapCRM.Services.FieldAPI.Models.Rapport_Visite", "Id_Visite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visite");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Visite", b =>
                {
                    b.HasOne("CynapCRM.Services.FieldAPI.Models.Planning_Visite", "Planning")
                        .WithMany("Visites")
                        .HasForeignKey("Id_Planning")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Planning_Visite", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("CynapCRM.Services.FieldAPI.Models.Visite", b =>
                {
                    b.Navigation("Rapport");
                });
#pragma warning restore 612, 618
        }
    }
}
