// <auto-generated />
using System;
using CynapCRM.Services.DocAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.DocAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518000718_NVDoc")]
    partial class NVDoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.DocAPI.Models.Document", b =>
                {
                    b.Property<int>("Numero_Doc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero_Doc"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Client")
                        .HasColumnType("int");

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nom_Doc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Numero_Doc");

                    b.HasIndex("Id_Client");

                    b.HasIndex("Id_Commande");

                    b.ToTable("T_Documents_Commerciaux", (string)null);

                    b.HasDiscriminator<string>("TypeDocument").HasValue("GENERIC");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CynapCRM.Services.DocAPI.Models.BonCommande", b =>
                {
                    b.HasBaseType("CynapCRM.Services.DocAPI.Models.Document");

                    b.HasDiscriminator().HasValue("BC");
                });

            modelBuilder.Entity("CynapCRM.Services.DocAPI.Models.BonLivraison", b =>
                {
                    b.HasBaseType("CynapCRM.Services.DocAPI.Models.Document");

                    b.HasDiscriminator().HasValue("BL");
                });

            modelBuilder.Entity("CynapCRM.Services.DocAPI.Models.Facture", b =>
                {
                    b.HasBaseType("CynapCRM.Services.DocAPI.Models.Document");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("FACTURE");
                });
#pragma warning restore 612, 618
        }
    }
}
