// <auto-generated />
using System;
using CynapCRM.Services.OrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.OrderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.Commande", b =>
                {
                    b.Property<int>("Id_Commande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Commande"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Client")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotalHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id_Commande");

                    b.HasIndex("Id_Client");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id_Ligne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ligne"));

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<decimal>("Remise")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id_Ligne");

                    b.HasIndex("Id_Commande");

                    b.HasIndex("Id_Produit");

                    b.HasIndex("NumeroLot");

                    b.ToTable("LignesCommandes");
                });

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.Reclamation", b =>
                {
                    b.Property<int>("Id_Rec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rec"));

                    b.Property<DateTime>("DateReclamation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Client")
                        .HasColumnType("int");

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Rec");

                    b.HasIndex("Id_Commande");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.LigneCommande", b =>
                {
                    b.HasOne("CynapCRM.Services.OrderAPI.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("Id_Commande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.Reclamation", b =>
                {
                    b.HasOne("CynapCRM.Services.OrderAPI.Models.Commande", "Commande")
                        .WithMany("Reclamations")
                        .HasForeignKey("Id_Commande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("CynapCRM.Services.OrderAPI.Models.Commande", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Reclamations");
                });
#pragma warning restore 612, 618
        }
    }
}
