// <auto-generated />
using System;
using CynapCRM.Services.InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.InventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326203426_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Echantillon", b =>
                {
                    b.Property<int>("Id_Distribution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Distribution"));

                    b.Property<DateTime>("DateDistribution")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Medecin")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.HasKey("Id_Distribution");

                    b.HasIndex("Id_Medecin");

                    b.HasIndex("NumeroLot");

                    b.ToTable("Distributions_Echantillons", (string)null);
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue", b =>
                {
                    b.Property<int>("Id_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_stock"));

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QteDisponible")
                        .HasColumnType("int");

                    b.Property<string>("TypeStock")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id_stock");

                    b.HasIndex("Id_User_Delegue");

                    b.HasIndex("NumeroLot");

                    b.ToTable("Stocks", (string)null);

                    b.HasDiscriminator<string>("TypeStock").HasValue("Standard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Echantillon", b =>
                {
                    b.HasBaseType("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue");

                    b.Property<int>("QteEchantillon")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Echantillon");
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Gratuite", b =>
                {
                    b.HasBaseType("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue");

                    b.Property<int>("QteGratuite")
                        .HasColumnType("int");

                    b.Property<string>("TypePromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Gratuite");
                });
#pragma warning restore 612, 618
        }
    }
}
