// <auto-generated />
using System;
using CynapCRM.Services.InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CynapCRM.Services.InventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Echantillon", b =>
                {
                    b.Property<int>("Id_Distribution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Distribution"));

                    b.Property<DateTime>("DateDistribution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Id_Delegue")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Medecin")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Pharmacien")
                        .HasColumnType("int");

                    b.Property<int>("Id_Stock")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.HasKey("Id_Distribution");

                    b.HasIndex("Id_Medecin");

                    b.HasIndex("Id_Pharmacien");

                    b.HasIndex("NumeroLot");

                    b.ToTable("Distributions_Echantillons", (string)null);
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.StockMovement", b =>
                {
                    b.Property<int>("Id_Movement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Movement"));

                    b.Property<DateTime>("DateMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Stock")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("TypeMovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Movement");

                    b.HasIndex("Id_Stock");

                    b.ToTable("Stock_Movements", (string)null);
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue", b =>
                {
                    b.Property<int>("Id_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_stock"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Delegue")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QteDisponible")
                        .HasColumnType("int");

                    b.Property<int>("QteReservee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TypeStock")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id_stock");

                    b.HasIndex("Id_User_Delegue");

                    b.HasIndex("NumeroLot");

                    b.ToTable("Stocks", (string)null);

                    b.HasDiscriminator<string>("TypeStock").HasValue("Standard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Echantillon", b =>
                {
                    b.HasBaseType("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue");

                    b.Property<int>("QteEchantillon")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Echantillon");
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.Stock_Gratuite", b =>
                {
                    b.HasBaseType("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue");

                    b.Property<int>("QteGratuite")
                        .HasColumnType("int");

                    b.Property<string>("TypePromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Gratuite");
                });

            modelBuilder.Entity("CynapCRM.Services.InventoryAPI.Models.StockMovement", b =>
                {
                    b.HasOne("CynapCRM.Services.InventoryAPI.Models.Stock_Delegue", null)
                        .WithMany()
                        .HasForeignKey("Id_Stock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
